### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by martimpassos** [imaginerio/omeka-s-docker#6]
Our HTTPS request to Omeka's API is currently unverified, please renew the certificate when possible

**Comment by davidheyman** [comment]
I've renewed the certificate so we should be all set. If it is still failing, can you let me know the specific request that isn't working?

![2020-08-06_00-22-04](https://user-images.githubusercontent.com/791434/89473495-e4a19c80-d77a-11ea-8ea2-efb73037ad97.png)
